### ISSUE TITLE
Setup endpoint crate structure and required dependencies

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush-rs#102]
Create the autoendpoint crate, copy/update main/settings from autopush and setup basic module structure with the actix framework.

**Comment by pjenvey** [comment]
When creating a new `Settings` type for the `autoendpoint` crate, let's see if we can take advantage of somewhat recent changes to `config-rs`'s handling of defaults. More details about this are over here as a [TODO for syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs/issues/253)

**Comment by pjenvey** [comment]
We've used very similar actix-web project skeletons in syncstorage-rs and recently [tokenserver-rs](https://github.com/mozilla-services/tokenserver-rs/pull/7)

**Comment by Mcat12** [comment]
@jrconlin set up a template in https://github.com/mozilla-services/autoendpoint-rs so I'll apply the work I've done up to now to that repo (and link with `autopush-common`) and then call this issue finished.

**Comment by Mcat12** [comment]
A discussion was held about having a separate repo vs using this repo, conclusion is to use this repo for now and switch over to a separate repo if it's not working out.
