### ISSUE TITLE
cleanup cargo clippy warnings

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush-rs#112]
It's been a while since we went through the clippy warnings and since then they've piled up.

We should run cleanup all the incidents of `cargo clippy -- -W clippy::clone_on_ref_ptr` violations

**Comment by jrconlin** [comment]
heh, at this point, I just want 126 to land.

But, yeah, cleaning up the clippy warnings should be done.

**Comment by Mcat12** [comment]
There are currently no more clippy warnings.
