### ISSUE TITLE
Find a workaround for HTTP/2 headers issue within GCP.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/autopush-rs#123]
Filing this to track progress.

[Support case with GCP](https://console.cloud.google.com/support/cases/detail/20994801?organizationId=442341870013&caseId=20994801&accountId=gcp-sa-1256631965)

**Comment by pjenvey** [comment]
Oops, wrong repo! :grinning:

Moved here: https://github.com/mozilla-services/syncstorage-rs/issues/293

**Comment by tublitzed** [comment]
thanks, @pjenvey. Also, I recently found you can actually move the same issue from one repo to another.
