### ISSUE TITLE
Double amount of headers allowed

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#136]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1623400

We currently limit to 16 headers, which is insufficient for expected demands, particularly with increased numbers of "Sec-*" headers being provided by nightly.

Current header list may include:
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive, Upgrade
Host: push.services.mozilla.com
Origin: wss://push.services.mozilla.com/
Pragma: no-cache
Sec-Fetch-Dest: websocket
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: cross-site
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: eyGFCl0x3LtrfBzjknmISg==
Sec-WebSocket-Protocol: push-notification
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 ...
```
*Note:* this will return a Severity: 7 error `"Fields":{"msg":"127.0.0.1:46460: too many headers"}`. I suspect this is not being logged. We may wish to increase visibility of this error in the future.

**Comment by jrconlin** [comment]
argh.

So, `cargo audit` has identified a vuln with hyper. so we're now blocked by #133

**Comment by fzzzy** [comment]
Can we tell cargo audit to ignore it somehow, and get this fixed before updating hyper? I'll get our hyper updated asap, but we shouldn't block this bug on it.
