### ISSUE TITLE
Only register user on new subscription request

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#137]
[Bug 1617136](https://bugzilla.mozilla.org/show_bug.cgi?id=1617136) will increase the number of writes we currently are making to DynamoDB. 

In order to reduce those, we should consider only recording the now quite disposable UAID we issue in the `hello` message when we absolutely need to.

~From doing a cursory overview of the code, I believe it's possible to alter `DynamoDbUser` to include the `chids`, modify `handle_user_result` to fetch the uaid meta record containing the chids, and then use that to determine if `hello` should call `register_user` if `chids` are not empty.~ (Optionally, we could also include a `registered` boolean inside of DynamoDB to indicate if this user is registered or not)

*IF* the client is well behaved, we should only get a UAID when there are existing ChannelIDs. We could verify by performing an UPDATE write to the Router Table, returning a new UAID if that fails (and possibly resetting any `registered` flags, since the UA is now effectively unregistered.)

On any future `register` call, we can either first check if `registered` is `false` or just call `register_user` with the values already set in `DynamoDbUser` to record the user into the `router` table, then proceed to record the new information for the `message*` table.

**Comment by tublitzed** [comment]
Based on what we found [here](https://github.com/mozilla-services/services-engineering/issues/47) going to de-prioritize for now.

**Comment by jrconlin** [comment]
BLOCKED on https://github.com/mozilla-services/autopush-rs/pull/143
