### ISSUE TITLE
[autoendpoint] Add sentry support to web handlers

### ISSUE THREAD

**Issue by Mcat12** [mozilla-services/autopush-rs#155]
Top-level panics are caught by sentry already, but panics and other errors in Actix handlers are caught at the worker level by Actix instead of sentry.

Some possible solutions:
- https://docs.rs/sentry-actix/
  It's not clear if this library will catch errors thrown by other middleware, but perhaps this isn't important if we don't use other middleware.
- https://github.com/mozilla-services/syncstorage-rs/blob/master/src/web/middleware/sentry.rs
  Already in use by syncstorage, handles errors thrown by other middleware, but is kind of a hack.

**Comment by jrconlin** [comment]
Yeah, the sentry middleware is definitely a hack. The original [actix author felt](https://github.com/actix/actix-web/issues/1051) that errors should not progress into the middleware and should be handled by the functions. I don't know if that issue will be re-opened now that the project is under different management.

**Comment by pjenvey** [comment]
actix-web middleware is just not super friendly to use as of actix-web 1.0.

They require some extra boilerplate to use (the `Transform`), use their own ServiceRequest/ServiceResponse (vs the regular HttpRequest/Response) which can be limiting particularly once they're consumed by calling into the wrapped middleware (e.g. `self.service.call(sevice_request)`).

With all these drawbacks + the strange error handling, I generally don't recommend using actix-web middlewares at all unless there's a *very* compelling reason and or it's for something very simple.

**Comment by Mcat12** [comment]
Using extractors (`FromRequest`) may be a better way to achieve some of what we need.

**Comment by Mcat12** [comment]
`sentry-actix` does not support Actix 1.0, so we may have to re-use our "hack" middleware:
https://github.com/getsentry/sentry-rust/issues/143

**Comment by Mcat12** [comment]
This issue is now deprioritized, but here are some learnings:
- `sentry` 0.18 does not support `std::error::Error`, and some useful utilities (i.e. `backtrace_to_stacktrace`) are private. `sentry` 0.19 fixes most of these problems. We need to upgrade sentry before this issue can be completed.
- `sentry` 0.19 splits into multiple crates (`sentry-core`, `sentry-backtrace`, etc). The `sentry` crate combines these and acts like the 0.18 version (feature flags to select features). We should continue to use the `sentry` crate because it provides the transport integrations (curl).
- Since `sentry-actix` does not work with Actix 1.0, we need to write our own middleware. The one used in syncstorage-rs is complicated by support for errors in middleware. We can make a simpler sentry middleware by not supporting errors in middleware.
- We can write our own Sentry Actix middleware pretty easily via `App::wrap_fn`:
  ```rust
  App::new().wrap_fn(sentry_middleware)

  // ...

  fn sentry_middleware(
      req: ServiceRequest,
      service: &mut impl Service<
          Request = ServiceRequest,
          Response = ServiceResponse,
          Error = actix_web::Error,
      >,
  ) -> impl Future<Output = Result<ServiceResponse, actix_web::Error>> {
      let response = service.call(req);

      async move {
          let response: Result<ServiceResponse, actix_web::Error> = response.await;
          // Check for error and send to sentry
          response
      }
  }
  ```

**Comment by Mcat12** [comment]
Bumped to 5 due to sentry not working with Actix 1.0/2.0. We need to make our own middleware.
