### ISSUE TITLE
Utilize regexes in route matches

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush-rs#158]
actix-web's routes [support regexes](https://github.com/actix/actix-website/blob/7a973d6/content/docs/url-dispatch.md#resource-pattern-syntax) (_Within braces, the replacement marker name must be followed by a colon, then directly thereafter, the regular expression._), so I believe we can port over at least some of the same (or similar) re patterns from the Python code.

The applicable ones match formats: e.g. for api_ver `/wpush/(?:(?P<api_ver>v\d+)...`.

**Comment by Mcat12** [comment]
I think the ways we use regex in the routes can be handled without regex. Almost all of the regex uses the snippet `(?P<variable_name>[^\/]+)`, which is just a path segment, and is represented by Actix as a normal path variable: `/my/api/{variable_name}/path`.

The one case where real regex functionality is used is for the optional API version. This is more idiomatically handled by providing two routes:
https://github.com/mozilla-services/autopush-rs/blob/b08fdbdd61edbc817835ab0fb18f304fd6fda505/autoendpoint/src/server/mod.rs#L50

I don't see any other usages of regex, so perhaps this issue isn't needed?

**Comment by pjenvey** [comment]
I thought I saw one more usage but that one's for the connection node's `/notif/`.

It certainly can be handled elsewhere, feel free to close this out if it's not needed.

**Comment by Mcat12** [comment]
Thanks for thinking of this!
