### ISSUE TITLE
[autoendpoint] Route FCM notifications

### ISSUE THREAD

**Issue by Mcat12** [mozilla-services/autopush-rs#162]
WebPush notifications (destined for Android user agents using FCM) should be routed through Firebase Cloud Messaging.

Questions:
- Do both versions of FCM need to be supported (legacy and v1)?
  Answer: Only support v1

**Comment by Mcat12** [comment]
#163 was closed because we can route GCM messages with legacy FCM. However, now the question is if can we route legacy FCM over v1 FCM, removing the need to support legacy FCM.

**Comment by Mcat12** [comment]
Furthermore, GCM no longer functions:
> The GCM server and client APIs were removed on May 29, 2019, and currently any calls to those APIs can be expected to fail.

https://developers.google.com/cloud-messaging

We should remove "gcm" from the list of valid router types.

**Comment by Mcat12** [comment]
FCM legacy and v1 can both handle FCM messages, so we should at least support v1. @jrconlin Given this, is there any reason we should also support FCM legacy?

**Comment by jrconlin** [comment]
No. We can drop GCM and FCM legacy at this point.
