### ISSUE TITLE
Drop user routing information if bridge reports 404/410 or similar error

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#173]
If the bridge system reports a user is no longer registered or found, we should drop that user from our routing table. 

Companion to:

https://github.com/mozilla-services/autopush/issues/1414

**Comment by jrconlin** [comment]
Going to reassign to @Mcat12, since this would be part of the endpoint work, which has not yet officially landed into autopush.

**Comment by Mcat12** [comment]
Note: although #197 closes this issue, to-be-implemented routers (Apple and Amazon) will still have to take this into account.
