### ISSUE TITLE
[autoendpoint] Support unregister user endpoint

### ISSUE THREAD

**Issue by Mcat12** [mozilla-services/autopush-rs#179]
Endpoint: `DELETE /v1/{type}/{app_id}/registration/{uaid}`
Documentation: https://autopush.readthedocs.io/en/latest/http.html#unregister-uaid-and-all-associated-channelid-subscriptions

Deletes the user and all channels.

**Questions:**
- Should this also delete all pending messages for the user in the message table?
  A: Yes. once a user is deleted, all data associated with the user should also be deleted.
  https://github.com/mozilla-services/autopush-rs/issues/179#issuecomment-660349218

**Comment by jrconlin** [comment]
A: Yes. once a user is deleted, all data associated with the user should also be deleted.

**Comment by Mcat12** [comment]
It turns out that in order to delete all of the user's rows in the message table, we would need to scan for them and batch delete them:
https://stackoverflow.com/questions/34259358/dynamodb-delete-all-items-having-same-hash-key

The Python code simply deletes the row in the router table (not touching the message table). Should we continue to use this behavior or follow the suggestion from the StackOverflow post?
