### ISSUE TITLE
Provide documentation and tooling for generating key values

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#217]
In the python version, we provided instructions on how to generate the fernet crypto_key and other values. It might be worth bringing over the `autokey.py` into tools and providing some additional docs for how to get it working.

**Comment by Mcat12** [comment]
I think the Fernet crypto key is the only key that we need to document and provide tooling for? (or at least it's the only one that is documented for Python autopush)

**Comment by jrconlin** [comment]
I think you're right. I was looking around to see if there were any others. 
IIRC: the key values autopush has are:

* The endpoint fernet key: `crypto_key` 
* Endpoint Auth key: `auth_key`
* UAID hash `key_hash`

If folks wanted, they could use the same tool to generate the other values as well, but we should note they should be a different values than the fernet key to keep folks from making silly mistakes.

**Comment by Mcat12** [comment]
Is UAID key hashing still in use? AFAIK, it isn't and it hasn't been re-implemented in Rust. We can add it back in though if that's required.

**Comment by jrconlin** [comment]
It's complicated?

The UAID hash was originally suggested to us by an OpSec member, after roll out. We don't currently use it in our production because it would invalidate older records, but if anyone were to set up their own Push server, it's not a terrible idea because it provides some security against correlation if the data were to ever leak out.
