### ISSUE TITLE
Autopush should accept JSON formatted env args

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#234]
Some args are compound and are normally expressed as JSON.  (e.g. AUTOEND_CRYPTO_KEYS, fcm creds, etc.)
Ops already has these as JSON, so we should make sure they're accepted.

**Comment by Mcat12** [comment]
I think most of those keys accept the JSON/JSON-like inputs, but the routers have different settings and possibly different structure (though cryptokeys is the same input format I think). See the various `settings.rs` files for details.

Also see the sample config:
https://github.com/mozilla-services/autopush-rs/blob/master/configs/autoendpoint.toml.sample

**Comment by jrconlin** [comment]
Yeah, the problem is that ops has well formed JSON that they use in the ENV args (meaning quoted key strings in arrays e.g. `["foo", "bar"]` which causes an error with the current version. The sample one is wrong, and also needs to be corrected (thanks). For the most part, I don't think that we really need to do full JSON parsing, but we should add testing at least that uses a fully qualified JSON config string.
