### ISSUE TITLE
Move forked "a2" dependency into mozilla-services org

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/autopush-rs#236]
Following best practices to not tie production code to our personal repos, let's move [this dep](https://github.com/mozilla-services/autopush-rs/blob/master/autoendpoint/Cargo.toml#L15) out of a personal repo and into the mozilla-services org before we deploy this to prod.

**Comment by Mcat12** [comment]
Let me know if you need any help from me.

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/a2

**Comment by tublitzed** [comment]
@jrconlin can we also change the dependency in this repo to point to the newly created https://github.com/mozilla-services/a2? https://github.com/mozilla-services/autopush-rs/blob/master/autoendpoint/Cargo.toml#L15

**Comment by jrconlin** [comment]
We may want to consider either owing a specific fork of this library, or replacing it with a more actively supported library, since the original library seems to be abandoned.

**Comment by tublitzed** [comment]
Yup - worth looking at for sure. In the meantime, can we scope this ticket to simply replacing the link to a personal repo with something that we own? After that, we can look at replacing the lib separately.
