### ISSUE TITLE
autoendpoint: modify FCMCredentials to accept String

### ISSUE THREAD

**Issue by oremj** [mozilla-services/autopush-rs#254]
Can we modify FCM credentials to accept a string instead of PathBuf? It looks like the yup_oauth2 library only supports a Path in `read_service_account_key`, but perhaps we could create a temp file out of the auth file string and pass that to the library?

**Comment by jrconlin** [comment]
Maybe? Kind of the point you're making here. There might be a way to do it using file handoffs, but it's going to be messy because I don't always know if I have write access.

I can try writing to `/tmp` but I wonder if that might be a security concern.

**Comment by pjenvey** [comment]
The `ServiceAccountKey` it returns is just a json deserialization of the creds and it's public, so we should be able to just deserialize directly to it from the env String.

See the [`read_service_account_key` code](https://docs.rs/yup-oauth2/5.0.3/src/yup_oauth2/helper.rs.html#42-50) for what I mean

**Comment by oremj** [comment]
> The `ServiceAccountKey` it returns is just a json deserialization of the creds and it's public, so we should be able to just deserialize directly to it from the env String.
> 
> See the [`read_service_account_key` code](https://docs.rs/yup-oauth2/5.0.3/src/yup_oauth2/helper.rs.html#42-50) for what I mean

This is a good point and likely a good way around the tmp file solution.
