### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#265]
Currently [our documentation](https://autopush.readthedocs.io/en/latest/index.html) is auto-generated and posted to ReadTheDocs.io. We currently have not implemented this for Rust, and I strongly suspect that things will quickly age out. 

We should investigate and implement how to incorporate, autogen, and publish the same docs with this new repo.

**Comment by Mcat12** [comment]
Duplicate of #264?

**Comment by jrconlin** [comment]
Heh, yeah, RIght idea, wrong repo. *sigh* been that kinda day.
