### ISSUE TITLE
Add metrics for FCM error responses

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#288]
We currently do not record metrics for the 404, 410, and invalid token responses we get back from FCM. This means we are working in the dark when determining the sorts of faults we see with Send Tab. 

As a preliminary step, we should record a metric. We may also want to return this status back, however that may leak if a given endpoint was an android user.

**Comment by pjenvey** [comment]
We do emit a bridge error metric on 404/410, but we don't distinguish between them (or their errnos)

**Comment by jdragojevic** [comment]
@jrconlin  - when do you expect this to get finished?

**Comment by jrconlin** [comment]
This is currently in review. 
I've pinged pjenvey to see if he can review and land this soon. (sorry, we've had a lot on our plates, this probably fell off)

**Comment by jrconlin** [comment]
See also [Jira ticket](https://mozilla-hub.atlassian.net/browse/CONSVC-1308)
