### ISSUE TITLE
Add metrics to record desktop Push usage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/autopush-rs#336]
Our metrics tend to be reactive, only measuring things that were a concern. This means that we have good coverage for mobile devices, but no coverage for desktop.

We should add some metrics around desktop delivery to indicate the desktop platform OS.

We should be able to add this information as tag info to `ua.notification.sent`, `notification.message_data`, `ua.command.hello`, and other similar metric messages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3516)

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

Added to https://github.com/mozilla-services/autopush-rs/pull/330 ( https://github.com/mozilla-services/autopush-rs/pull/330|smart-link )

**Comment by jrconlin** [comment]
Added to https://github.com/mozilla-services/autopush-rs/pull/330

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Released with 1.66.
