### ISSUE TITLE
Ignore the "message is intended for a constrained device" error/event

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/autopush-rs#347]
We currently ignore this very chatty error on sentry:

[https://sentry.io/organizations/mozilla/issues/3284213212/?environment=prod&project=6326250&query=is%3Aignored&referrer=issue-stream](https://sentry.io/organizations/mozilla/issues/3284213212/?environment=prod&project=6326250&query=is%3Aignored&referrer=issue-stream)

Per [~accountid:6047c59f43eac6006f71fbd3] these are expected, so we should stop emitting them to sentry entirely. Even with the sentry level ignore, the number of these emitted (=~ 1500 an hour) cause us to exceed our quota, triggering Sentry to drop a significant number of events.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3582)

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

Git Blame says that this was fixed by #327 ( https://github.com/mozilla-services/autopush-rs/pull/327 ), which is part of 1.66.0 ( https://github.com/mozilla-services/autopush-rs/releases/tag/1.66.0 ), which has not been deployed to production ( https://updates.push.services.mozilla.com/__version__ ) yet.

**Comment by jrconlin** [comment]
1.66 is in production
