### ISSUE TITLE
Remove table rotation from Autopush

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#373]
Originally, we could only clean up old records by rotating message storage tables. We've not used that since the last table rotation in 2017. 

The table rotation code adds needless complexity that impacts other data stores. (We should probably retain DynamoDB support in case the company shifts cloud platforms again in the future.)

Let's remove the table rotation code and simplify the storage systems.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3703)

**Comment by data-sync-user** [comment]
➤ Philip Jenvey commented:

The leftover legacy rotating message table code I’m seeing:

  * The db User::current_month field
  * The DbClient::rotating_message_table trait method
  * The associated code/docs that utilize the above to “validate” users: both in autoendpoint and autoconnect (autoconnect_ws_sm’s process_existing_user function should probably go away entirely)
