### ISSUE TITLE
Why not use redis intead of DynamoDB for storing the map between a CEP and a device?

### ISSUE THREAD

**Issue by GingerMoon** [mozilla-services/autopush-rs#540]
Hi guys, I am very curious why not use redis intead of DynamoDB for storing the map between a CEP and a device?
If a shard of the redis cluster is down, we can just break the connections between the CEPs (of the broken redis shard) and the devices.
I am asking is because the cost of DynamoDB CPU should be higher than redis memory cost, right?
(sorry if this question is so stupid, any insights would be much appreciated)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4052)

**Comment by jrconlin** [comment]
Put simply, it was about cost, from several angles. 

At the time, we had several discounts around DyanmoDB that made it very attractive to use. In our case, we could use DynamoDB for all aspects of Autopush and not incur additional costs of running a redis server in addition to DyanmoDB. 

There's also issues around outages. If DyanmoDB goes out (which it does from time to time) we don't lose all the pending messages for users, the channels that they had already established, endpoints, etc. We can't do anything until the database comes back up, but it will come back up. With Redis, we could turn on some of the archive function, but then we lose a lot of the performance and cost savings. 

Does that help answer the question?

**Comment by GingerMoon** [comment]
Yeah, that makes sense! Thanks a lot @jrconlin for sharing the insight!
