### ISSUE TITLE
Bigtable remove_message assumes topic message style chidmessageids

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/autopush-rs#552]
It looks for a channel_id in the wrong place for non topic messages.

remove_message isn’t really used for timestamp messages, so no tests actually caught this, but it should be fixed regardless.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4065)

**Comment by jrconlin** [comment]
For further clarification, we should probably use `NotificationRecord::parse_chidmessageid()` for this.
