### ISSUE TITLE
Upgrade Python in Autopush Test Solutions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/autopush-rs#594]
Update the Python test solutions to use the latest version of Python.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4078)

**Comment by data-sync-user** [comment]
➤ Katrina Anderson commented:

Currently the load tests use pypy 3.10, we would have to test the impact of removing this dependency, which is blocked by https://mozilla-hub.atlassian.net/browse/SYNC-4082 ( https://mozilla-hub.atlassian.net/browse/SYNC-4082|smart-link ).

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

heh, the google console is still on Python 3.9.2. I’m guessing the default image hasn’t been updated in a while.

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

hey JR Conlin ! I see python:3.10-slim-bullseye in our ci config for py checks, 3.10-slim-bookworm in load testing. Do you mean that once deployed on GCS, it's 3.9.2 as defined in the cluster? In that case do we need to get SRE to update that for us? Just curious since our Dockerfile in merino lined up with the ci config, which were the same

**Comment by jrconlin** [comment]
I was noting that the default installed python on the GCP system host is 3.9.2. As I understand, we use kubernetes to deploy, so we can use any version provided there's an appropriate docker image associated with it. 

That said, I didn't know that we have different versions of the system. That seems less good. You're right that we should be consistent about the version of python and the base system we run off of.

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

hey Katrina Anderson ! We can go over this together to determine if there is/would be any impact to the load tests. There are a handful of deprecation messages yielded by the update to Python 3.12, however those will be handled in https://mozilla-hub.atlassian.net/browse/SYNC-4188 ( https://mozilla-hub.atlassian.net/browse/SYNC-4188|smart-link )

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Went over calibration protocol with @Trinaa ( https://github.com/Trinaa ) (thanks Kat!) which she is adding in this pr ( https://github.com/mozilla-services/autopush-rs/pull/661 ). Verified new python version image python:312 (changed from pypy:3.10 does not degrade or require a reduction of workers in load tests. Verified in both user classes, CPU and memory usage minimal (10% CPU) same for memory. See autopush load test spreadsheet log entry for 2024-03-14(https://docs.google.com/spreadsheets/d/1-nF8zR98IiLZlwP0ISwOB8cWRs74tJGM1PpgDSWdayE/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1-nF8zR98IiLZlwP0ISwOB8cWRs74tJGM1PpgDSWdayE/edit#gid=0|smart-link ) )
