### ISSUE TITLE
Include debuginfo in release builds

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush-rs#77]
We can include debuginfo in our release builds for minimal performance hit, but more meaningful errors.

**Comment by bbangert** [comment]
https://github.com/rust-lang/rust/issues/49227 has some help on this

**Comment by pjenvey** [comment]
Copying over my explanation from https://github.com/mozilla-services/syncstorage-rs/pull/91 for reference here:

> Took me a while to track this down, we came across it for [autopush-rs](https://github.com/mozilla-services/autopush-rs/issues/77). There's also a not well documented debug value of either 1 (or 2, but true is the equivalent of 2). This value's passed along to rustc -C debuginfo:
> 
> ```
>     -C            debuginfo=val -- debug info emission level, 0 = no debug info, 1 = line tables only, 2 = full debug info with variable and type information
> ```
> 
> `debug = 1` sounds ideal for release builds, just producing the line tables
> 
> There's been some reports of slowdowns with full release = 2 which may or may not be fixed:
> 
> [rust-lang/rust#49227](https://github.com/rust-lang/rust/issues/49227)
> 
> debug = 1 should at the very least reduce the binary size

**Comment by pjenvey** [comment]
Some additional info here: https://github.com/BurntSushi/ripgrep/issues/413
